### ISSUE TITLE
I have meet some problem

### ISSUE THREAD

**Issue by harlanhong** [apoorvavinod/Real_time_Object_detection_and_tracking#1]
I got : module 'cv2.cv2' has no attribute 'MultiTracker_create' when I run you code , and my opencv version    
is 3.4.0 ,

**Comment by apoorvavinod** [comment]
Please check if your OpenCV build contains modules from opencv_contrib

**Comment by apoorvavinod** [comment]
You can install the contrib modules following this tutorial : http://www.pyimagesearch.com/2016/10/24/ubuntu-16-04-how-to-install-opencv/

Or the following one for windows: https://stackoverflow.com/questions/37517983/opencv-install-opencv-contrib-on-windows

Brew offers an easy install as well.
