### ISSUE TITLE
Multiple Objects not tracked in some videos.

### ISSUE THREAD

**Issue by sharadhigm** [apoorvavinod/Real_time_Object_detection_and_tracking#10]
Hi I would like to know when real time video is run for detection and tracking,sometimes,multiple people in frame are not detected and tracked back if they move out of frame and return..Why that may be so?Can u also help how i can detect and track only every 10th frame?
darknet supports -s flags that controls "skip frames".how can that be implemented here as well?

**Comment by apoorvavinod** [comment]
1. New detections are made only when all the current detected objects are lost in the frame or manually when 'q' is pressed. When I say a detected object is lost, I mean when the tracker for the object reports a failure.
2. I would keep a counter to keep track of the number of frames you want to skip. As soon as the number of frames you want to skip is reached, you can call 'intermediate_detections'.
