### ISSUE TITLE
I need re-init my kcftracker ,but I guess the opecv kcf dont have the function.

### ISSUE THREAD

**Issue by zhujinchao123** [apoorvavinod/Real_time_Object_detection_and_tracking#11]
I need re-init my kcftracker ,but I guess the opecv kcf dont have the function.
___________________________________________________________
such as ,
 -->KCFtrackers_dict[key] = cv.TrackerKCF_create()
 -->KCFtrackers_dict[key].init(frame, (ix1, iy1, w1, h1))  # the first init 
then may be some frames after update(KCFtracker.update(frame)),
then I re-init it ,
 -->KCFtrackers_dict[key].init(frame, (ix2, iy2, w2, h2))  # the second init 
  but ,in fact  the second init dont take effect!
__________________________________________________________
so ,I use other methed as follew :
-->KCFtrackers_dict.pop(key)
-->KCFtrackers_dict[key] = cv.TrackerKCF_create()
-->KCFtrackers_dict[key].init(frame, (ix, iy, w, h))
but it is too slow for the dict operate .
_________________________________________________________
so ,do you have other advice about the re -init ?
_________________________________________________________
uoip/KCFcpp-py-wrapper(in github ) ,his code can init many times .

but int his code dont return 'ok '(the flag to estimate wether the taget is lost )
such as :+1:  
 ok, bbox = KCFtracker.update(frame)

**Comment by apoorvavinod** [comment]
This is one of the problems I looked into while writing this code. OpenCV doesn't give the functionality to reinitialize the tracker, the only option you have is to delete the tracker and create a new tracker for the object. You might want to look at other tracker implementations as well. Try [dlib](https://pypi.org/project/dlib/) and [ImageAI](https://github.com/OlafenwaMoses/ImageAI), they might be more flexible than OpenCV

**Comment by zhujinchao123** [comment]
thank you for your reply ,i test the code need 0.033s for re-init in my way as follew .
--> KCFtrackers_dict.pop(key)
--> KCFtrackers_dict[key] = cv.TrackerKCF_create()
--> KCFtrackers_dict[key].init(frame, (ix, iy, w, h))
