### ISSUE TITLE
multi-target tracking

### ISSUE THREAD

**Issue by ericayn** [apoorvavinod/Real_time_Object_detection_and_tracking#13]
Thanks for your code. Can cv.TrackerKCF_create() achieve multi-target tracking? you use it in this code

**Comment by apoorvavinod** [comment]
cv.TrackerKCF_create() creates one instance of a tracker. That tracker tracks only one set of bounding boxes that you initialize it with. If you want multi-target tracking, you should use multiple trackers, one for each target.
