### ISSUE TITLE
can i use yolov3 as a detector ? 

### ISSUE THREAD

**Issue by adouwitti** [apoorvavinod/Real_time_Object_detection_and_tracking#14]
hello @apoorvavinod 
i hope that  you are doing well , i am going to use your repository that regards object detection and tracking ,  for tracking bus passengers. i trained my dataset with yolov3 , so , i wanted to ask you , if the performance will be same if i use yolov3 as a detector instead of yolov2. i tried to test with yolov3 , but the detection and tracking accuracy is not that much good. does the performance of the tracking depends on the yolo  model ? or i need to modify some parameters of kcf .  i would like that you help me. i am waiting for your response. thanks in advance

**Comment by apoorvavinod** [comment]
Hello, the detection performance depends on a lot of factors, for example the data your model trained on versus the data that the weights I have provided were trained on. The tracking performance is only affected by the detector at the initial stage when the bounding box for the object is initialized. But as far as actual tracking goes, it all depends on your tracker and its parameters. After you tweak your detector, I'd suggest experimenting with other trackers as well that are available in OpenCV. Also here are some repositories that you might find interesting:
https://github.com/sturkmen72/C4-Real-time-pedestrian-detection
https://github.com/mattzheng/keras-yolov3-KF-objectTracking
https://github.com/ITCoders/Human-detection-and-Tracking
https://github.com/ambakick/Person-Detection-and-Tracking

**Comment by adouwitti** [comment]
thanks for your response and clarifying the things. i will look at those links.

**Comment by adouwitti** [comment]
hello ,
i hope that you are doing well , i think that you used kcf tracker from
openCV. i wanted to change your code , because i want to implemented kcf
tracker (not from opencv). so i need to change only "process" function of
main file right ? . i am going to use yolov3  and caffe models as inputs ,
that why i am focused on your repository. your suggestions will be helpful
. thanks in advance.

**Comment by apoorvavinod** [comment]
Yes that's correct. You would need to change the part where you pass in each frame to update the co-ordinates of the bounding boxes. I will send you a few links to your mail which might help you.
