### ISSUE TITLE
How to integrate custom models trained on tensorflow object detection api?

### ISSUE THREAD

**Issue by gopalkalpande** [apoorvavinod/Real_time_Object_detection_and_tracking#18]
I have tried updating the object detection.py file in functions load_model as:
elif self.model.endswith('pb') and self.cfg.endswith('cofig'):
            print('in load_model: Tensorflow')
            self.net = cv.dnn.readNetFromTensorflow(self.cfg, self.model)
            self.framework = 'Tensorflow'

and in predict function as:
        elif self.framework == 'Tensorflow':
            print('blob:Tensorflow')  
            blob = cv.dnn.blobFromImage(cv.resize(frame, (300, 300)),0.007843, (300, 300), 127.5)

but it is not triggering the model and giving: 'Wrong input for model weights and cfg'

can you help me fix this? It can be a worthy update for the repo.
The way I updated the code:
![object_detection](https://user-images.githubusercontent.com/27803744/63016459-58370380-beb1-11e9-94c0-ebd34fe47a19.png)

**Comment by apoorvavinod** [comment]
`self.cfg.endswith('cofig')` Maybe its `config` that is misspelled as `cofig` ?
