### ISSUE TITLE
use this method for my own dataset

### ISSUE THREAD

**Issue by pordeli** [apoorvavinod/Real_time_Object_detection_and_tracking#19]
Hi.

How can I use this code for my own dataset for tracking multiple people in the video? What things should I change?

**Comment by AbuHelweh** [comment]
File "src/main.py", line 163, in process
    stream, objects_detected, objects_list, trackers_dict = intermediate_detections(stream, predictor, args.thr, classes)
  File "src/main.py", line 110, in intermediate_detections
    trackers_dict = {key : cv.TrackerKCF_create() for key in objects_list}
  File "src/main.py", line 110, in <dictcomp>
    trackers_dict = {key : cv.TrackerKCF_create() for key in objects_list}
AttributeError: module 'cv2.cv2' has no attribute 'TrackerKCF_create'

**Comment by apoorvavinod** [comment]
@pordeli Both models in this repo are trained to identify `people`. You can filter out other detections, and track just people if that is what you want.

**Comment by apoorvavinod** [comment]
@AbuHelweh Please install latest version of opencv with contrib modules. You can install the contrib modules following this tutorial : http://www.pyimagesearch.com/2016/10/24/ubuntu-16-04-how-to-install-opencv/

Or the following one for windows: https://stackoverflow.com/questions/37517983/opencv-install-opencv-contrib-on-windows

Brew offers an easy install as well on Mac.
