### ISSUE TITLE
AttributeError: module 'cv2.cv2' has no attribute 'MultiTracker_create'

### ISSUE THREAD

**Issue by cherishhh** [apoorvavinod/Real_time_Object_detection_and_tracking#2]
Traceback (most recent call last):
  File "src/main.py", line 252, in <module>
    main()
  File "src/main.py", line 249, in main
    process(args)
  File "src/main.py", line 138, in process
    multi_tracker = cv.MultiTracker_create()
AttributeError: module 'cv2.cv2' has no attribute 'MultiTracker_create'

**Comment by apoorvavinod** [comment]
MultiTracker modules are included in opencv-contrib. You can install the contrib modules following this tutorial : http://www.pyimagesearch.com/2016/10/24/ubuntu-16-04-how-to-install-opencv/

Or the following one for windows: https://stackoverflow.com/questions/37517983/opencv-install-opencv-contrib-on-windows

Brew offers an easy install as well.
