### ISSUE TITLE
AttributeError: module 'cv2' has no attribute 'INTER_AREA'

### ISSUE THREAD

**Issue by N0ODle** [apoorvavinod/Real_time_Object_detection_and_tracking#20]
Hello, I am starting to play around with your neural network to test it out, but I get an error every time I run the main.py file. Below is what I get:  

```
Traceback (most recent call last):
  File "src/main.py", line 12, in <module>
    import imutils
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/imutils/__init__.py", line 8, in <module>
    from .convenience import translate
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/imutils/convenience.py", line 65, in <module>
    def resize(image, width=None, height=None, inter=cv2.INTER_AREA):
AttributeError: module 'cv2' has no attribute 'INTER_AREA'
```

Please help me on how to resolve this issue. Thank you.

**Comment by quicktwit** [comment]
> Hello, I am starting to play around with your neural network to test it out, but I get an error every time I run the main.py file. Below is what I get:
> 
> ```
> Traceback (most recent call last):
>   File "src/main.py", line 12, in <module>
>     import imutils
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/imutils/__init__.py", line 8, in <module>
>     from .convenience import translate
>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/imutils/convenience.py", line 65, in <module>
>     def resize(image, width=None, height=None, inter=cv2.INTER_AREA):
> AttributeError: module 'cv2' has no attribute 'INTER_AREA'
> ```
> 
> Please help me on how to resolve this issue. Thank you.

It's mostly related to your OpenCV version.
