### ISSUE TITLE
Continuous Object Detection

### ISSUE THREAD

**Issue by Gregmann1** [apoorvavinod/Real_time_Object_detection_and_tracking#23]
Have tried to make this program continue object detection without pressing 'q'.  Video Feed locks up when attempting to add while loops for scanning.  

Is there any guidance available on how to detect new objects that come into the frame automatically?

**Comment by apoorvavinod** [comment]
You're essentially doing a forward pass through the neural network every time you try to detect objects. This is a compute intensive task. If it was easily for the GPU/CPU to handle, you'd just remove the tracking and do the forward pass each frame instead. But we don't have that amount of computing power, my suggestion would be to do the detection automatically once in a few seconds, or even better, setup some filter in OpenCV along with some logic that would detect when a new object comes into the frame, at which point you can trigger the object detection
