### ISSUE TITLE
The problem of 'label_with_num'

### ISSUE THREAD

**Issue by JL-Cheng** [apoorvavinod/Real_time_Object_detection_and_tracking#4]
**The 'label_with_num' of an object may be changed when another identical object enters the flame.**
_Like the people in the two pictures._
![default](https://user-images.githubusercontent.com/30789532/45293808-cea5e580-b52b-11e8-83a7-c88d6a43c510.png)
![1](https://user-images.githubusercontent.com/30789532/45293880-0a40af80-b52c-11e8-9a1c-7f2e060d7d13.png)
So do you have some solutions to this problem?

**Comment by apoorvavinod** [comment]
The way it is set up, the program tries to find new objects when

- There are no objects to be tracked in the current frame.
-  'q' is pressed.

These two conditions make the current frame go through forward pass of CNN and then new objects detected are listed for tracking. 
Currently, the objects being tracked before a new forward pass goes through, are discarded.

One way to make it remember old objects and hence maintain the old label_with_num values is to not discard the old objects during new forward pass and instead store them along with the new ones.

**Comment by JL-Cheng** [comment]
Ok, thank you. But the result of the improved program is not as good as expected , the accuracy rate is somewhat low. Especially when two objects are too close together, the fliter result always turns out to be wrong. So maybe I have to find some other approaches to this problem.

**Comment by apoorvavinod** [comment]
Do let me know if you find another solution that works well.
