### ISSUE TITLE
error: OpenCV(3.4.2) /io/opencv/modules/dnn/src/darknet/darknet_io.cpp:784: 

### ISSUE THREAD

**Issue by linzhi123** [apoorvavinod/Real_time_Object_detection_and_tracking#5]
self.net = cv.dnn.readNetFromDarknet(self.cfg, self.model)
error: OpenCV(3.4.2) /io/opencv/modules/dnn/src/darknet/darknet_io.cpp:784: error: (-212:Parsing error) Failed to parse NetParameter file: model_data/yolo.cfg in function 'ReadNetParamsFromCfgFileOrDie'

**Comment by apoorvavinod** [comment]
Glad I could help :)
