### ISSUE TITLE
could you give me some advice about how to use kcf track muti-object ?

### ISSUE THREAD

**Issue by zhujinchao123** [apoorvavinod/Real_time_Object_detection_and_tracking#8]
first of all its a good job for tracking by detection ,thank u for u good job.
1.  i guess you limit the kcf number for track ,because too many kcf will lead to code run slow.
2. do you use the cython to change kcf(c++)to python to use,because c++ is faster

**Comment by apoorvavinod** [comment]
Thank you,
1. I am not limiting the number of trackers as I did not intend this for production use. If you do want to put this in a real-world application, then yes..limiting number of detections and trackers is a good way to maintain performance. 
2. I am not using Cython to change the C++ KCF into Python. The KCF tracker I am using is the one provided by OpenCV. If I'm not mistaken, the python OpenCV(cv2) is a wrapper for the C++ version.

**Comment by zhujinchao123** [comment]
～～～～～～～～～～～～～～～～～～～～
ok, bbox = tracker.update(frame)  
                if ok:
                    objects_detected[obj][0] = bbox 
                else:
                    print('Failed to track ', obj)  
                    del_items.append(obj)  
～～～～～～～～～～～～～～～～～～～～

Question one :　I have question about the 'ok'.  it is a flag for whether KCF is lost .
                         Is it the Regression function？
　　　　　　　how can i use it more flexible , such as how i can control the degree for lost ?
～～～～～～～～～～～～～～～～～～～～
        if len(objects_detected) > 0:  
            drawPred(frame, objects_detected)
            cv.putText(frame, "FPS : " + str(int(fps)), (100,50), cv.FONT_HERSHEY_SIMPLEX, 0.75, (50,170,50), 2)
        else:
            cv.putText(frame, 'Tracking Failure. Trying to detect more objects', (50, 80), cv.FONT_HERSHEY_SIMPLEX, 0.75,(0,0,255),2)
            stream, objects_detected, objects_list, trackers_dict = intermediate_detections (stream, predictor, args.thr, classes) 
～～～～～～～～～～～～～～～～～～～～

Question two :　When len(objects_detected) ＝ 0　，　we use  intermediate_detections.
                         I think all the track must lost we can  intermediate_detections again , Can you give me                some  illuminating advice ?  really thank you for your reply .

～～～～～～～～～～～～～～～～～～～～
