### ISSUE TITLE
why I have not attribute 'TrackerKCF_create'?

### ISSUE THREAD

**Issue by zhujinchao123** [apoorvavinod/Real_time_Object_detection_and_tracking#9]
File "zjc_ssd_demo.py", line 401, in main
    KCFtrackers_dict = {key: cv.TrackerKCF_create() for key in objects_list}
  File "zjc_ssd_demo.py", line 401, in <dictcomp>
    KCFtrackers_dict = {key: cv.TrackerKCF_create() for key in objects_list}
AttributeError: module 'cv2.cv2' has no attribute 'TrackerKCF_create'
——————————————————————————————
import cv2
import cv2 as cv

my import is like above

**Comment by zhujinchao123** [comment]
my opencv is 3.0.0

**Comment by apoorvavinod** [comment]
3.0.0 is an older version. Try updating it to the latest one. (4.0 as of now)
